//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MyPhone.rc
//
#define ID_MSPACE                       0
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MYPHONE_DIALOG              102
#define IDS_PROGTITLE                   102
#define IDS_STARTCHANNELTX              103
#define IDD_AUDIOPAGE                   103
#define IDS_STARTCHANNELRX              104
#define IDS_STOPCHANNELTX               105
#define IDS_STOPCHANNELRX               106
#define IDS_STOPCONNECT                 107
#define IDS_TALKING                     108
#define IDR_OHICON                      128
#define IDA_OHICON                      128
#define IDR_MMAIN                       130
#define IDB_MYLOGOBMP                   131
#define IDD_GENERALPAGE                 138
#define IDD_VIDEOPAGE                   143
#define IDB_VIDEOBITMAP                 145
#define IDD_GUIPAGE                     146
#define IDR_LOGMENU                     147
#define IDR_DESTMENU                    149
#define IDI_MICICON                     150
#define IDI_MICMUTEICON                 151
#define IDI_SNDICON                     152
#define IDI_SNDMUTEICON                 153
#define IDD_GKPAGE                      171
#define IDI_TESTICON                    172
#define IDI_USERSICON                   173
#define IDI_CALLICON                    177
#define IDI_CALLANSWICON                178
#define IDI_CALLHANGICON                179
#define IDI_CALLREFICON                 180
#define IDI_LARRICON                    181
#define IDI_RARRICON                    182
#define IDD_NETWORKPAGE                 185
#define IDD_BOOKDIALOG                  187
#define IDD_BOOK_ADDR                   188
#define IDD_BOOK_OUT                    189
#define IDD_BOOK_IN                     190
#define IDD_BOOK_MISSED                 191
#define IDI_PHONE16                     192
#define IDI_COMP16                      193
#define IDI_PHONE16IN                   194
#define IDI_PHONE16OUT                  195
#define IDI_PHONE16MSD                  196
#define IDI_PHONE16UP                   197
#define IDI_PNPSHOW                     198
#define IDI_PNPHIDE                     199
#define IDD_VIDEOBOX                    200
#define ID_INDICATOR_IP                 201
#define ID_INDICATOR_TIME               202
#define IDS_NONETSTR                    203
#define IDS_PROXINETSTR                 204
#define IDS_UMSGSTR                     205
#define IDS_UIPSTR                      206
#define IDS_MPREADYSTR                  207
#define IDS_DSTCLEADEDSTR               208
#define IDS_DSTCLEAREDSTR               208
#define IDS_USAIDMSGSTR                 209
#define IDS_CALLINGSTR                  210
#define IDS_CALLING1STR                 211
#define IDS_STATFSTR                    212
#define IDS_STATSSTR                    213
#define IDS_RINGSTR                     214
#define IDS_RING1STR                    215
#define IDS_REPLMSGSTR                  216
#define IDS_MPREADY1STR                 217
#define IDS_ERRLSNSTR                   218
#define IDS_CALLIGNORSTR                219
#define IDS_TALKINGSTR                  220
#define IDS_CALLBUSYSTR                 221
#define IDS_ERRVDEVSTR                  222
#define IDS_GKUNREGSTR                  223
#define IDS_GKSRCHSTR                   224
#define IDS_GKREGSTR                    225
#define IDS_ERRSTR                      226
#define IDS_GKERRPORTSTR                227
#define IDS_GKERRALIASSTR               228
#define IDS_GKERRSECSTR                 229
#define IDS_GKERRTRNSTR                 230
#define IDS_GKERRUNSTR                  231
#define IDS_GKERRFINDSTR                232
#define IDS_GKERRFIND1STR               233
#define IDS_GKERRFIND2STR               234
#define IDS_GKERRFIND3STR               235
#define IDS_GKERRFIND4STR               236
#define IDS_CONNECTIONSTR               237
#define IDS_CALLTOSTR                   238
#define IDS_CALLBSTR                    239
#define IDS_ANSWERBSTR                  240
#define IDS_REFUSEBSTR                  241
#define IDS_HANGUPBSTR                  242
#define IDS_AUDIOSTR                    243
#define IDS_MSGSSTR                     244
#define IDS_VIDEOSTR                    245
#define IDS_LOCALSTR                    246
#define IDS_REMOTESTR                   247
#define IDS_MSETTINGSSTR                248
#define IDS_MABOUTSTR                   249
#define IDS_STRPROGNAMEVER              251
#define IDS_STRPROGDESC                 252
#define IDS_ABOUTSTR                    254
#define IDS_OUTDEVSTR                   255
#define IDS_INDEVSTR                    256
#define IDS_BUFFSTR                     257
#define IDS_JITSTR                      258
#define IDS_SLSTR                       259
#define IDS_CODECSSTR                   260
#define IDS_CADECSSTR                   260
#define IDS_CSUPSTR                     261
#define IDS_CSENBLSTR                   262
#define IDS_CSDOWNSTR                   263
#define IDS_USERSTR                     264
#define IDS_UNAMESTR                    265
#define IDS_NETWORKSTR                  266
#define IDS_BANDSTR                     267
#define IDS_KBSSTR                      268
#define IDS_IPTSTR                      269
#define IDS_AANSWERSTR                  270
#define IDS_DTMFSTRSTR                  271
#define IDS_D242STR                     272
#define IDS_DFSTARTSTR                  273
#define IDS_RINGFSTR                    274
#define IDS_GKUSESTR                    275
#define IDS_GKRECSTR                    276
#define IDS_GKLOCSTR                    277
#define IDS_GKAUTOLOCSTR                278
#define IDS_GKHOSTLOCSTR                279
#define IDS_GKIDLOCSTR                  280
#define IDS_GKPASSSTR                   281
#define IDS_UALIASESSTR                 282
#define IDS_UALIASSTR                   283
#define IDS_UALADDSTR                   284
#define IDS_UALDELSTR                   285
#define IDS_HVIDEOSTR                   286
#define IDS_HLOGSTR                     287
#define IDS_HSTATSTR                    288
#define IDS_ADRAUTOADDSTR               289
#define IDS_SYSTRAYMINSTR               290
#define IDS_LANGSTR                     291
#define IDS_COLSTR                      292
#define IDS_COLMSGSTR                   293
#define IDS_COLAUDIOSTR                 294
#define IDS_COLLSTR                     295
#define IDS_COLRSTR                     296
#define IDS_COLASTR                     297
#define IDS_COLSSTR                     298
#define IDS_DEVSTR                      299
#define IDS_DEVCHSTR                    300
#define IDS_VSENDSTR                    301
#define IDS_VRCVDSTR                    302
#define IDS_VLOCSTR                     303
#define IDS_VIESSTR                     304
#define IDS_VIEWSTR                     304
#define IDS_LVFLIPSTR                   305
#define IDS_LHFLIPSTR                   306
#define IDS_RVFLIPSTR                   307
#define IDS_RHFLIPSTR                   308
#define IDS_QTYSTR                      309
#define IDS_MBPSSTR                     310
#define IDS_GENERALSTR                  311
#define IDS_GKSTR                       312
#define IDS_IFACESTR                    313
#define IDS_SETTINGSSTR                 314
#define IDS_MHELPSTR                    315
#define IDS_PROGTRANSSTR                316
#define IDS_RTPBSTR                     317
#define IDS_RTPMSTR                     318
#define IDS_NATRSTR                     319
#define IDS_LOCISTR                     320
#define IDS_ABOOKSTR                    321
#define IDS_ABOOKTITLESTR               322
#define IDS_ABOOKADRNAMESTR             323
#define IDS_ABOOKADRADRSTR              324
#define IDS_ABOOKADRRINGSTR             325
#define IDS_SBOOKCALLSTR                326
#define IDS_ABOOKPBTITLESTR             327
#define IDS_ABOOKADRADDSTR              328
#define IDS_ABOOKADRDELSTR              329
#define IDS_ABOOKINTITLESTR             330
#define IDS_ABOOKOUTTITLESTR            331
#define IDS_ABOOKMSDTITLESTR            332
#define IDS_ABOOKADRSTORESTR            333
#define IDS_ABOOKADRCLRSTR              334
#define IDS_LOCFLIPSTR                  335
#define IDS_SINGLELINE                  336
#define IDS_FULLSCREEN                  337
#define IDS_AUTOMUTESTR                 338
#define IDC_DESTINATION                 1000
#define IDC_CALL                        1001
#define IDC_ANSWER                      1002
#define IDC_CALLER                      1003
#define IDC_REFUSE                      1004
#define IDC_HANGUP                      1005
#define IDC_STATUS                      1006
#define IDC_BTEST                       1007
#define IDC_BVIDPAN                     1007
#define IDC_ABOOK                       1008
#define IDC_PLAYBACK_COMBO              1009
#define IDC_USERMSG                     1009
#define IDC_RECORDING_COMBO             1010
#define IDC_EDIT_BUFFERS                1011
#define IDC_VIDDEVSRC_COMBO             1011
#define IDC_SPIN_BUFFERCOUNT            1012
#define IDC_SILENCE_DETECT_CHECK        1013
#define IDC_JITTER_EDIT                 1014
#define IDC_CODEC_SELECTION_LIST        1015
#define IDC_CS_UP_BUTTON                1016
#define IDC_CS_ENABLED_CHECK            1017
#define IDC_CS_DOWN_BUTTON              1018
#define IDC_SLIDER_VOLUME               1019
#define IDC_AEC_ENABLE                  1019
#define IDC_STITLE                      1020
#define IDC_AGC_EDIT                    1020
#define IDC_SLIDER_MIC                  1021
#define IDC_SVERSION                    1021
#define IDC_SCPRT                       1022
#define IDC_BANDWIDTH_COMBO             1023
#define IDC_SDESC                       1023
#define IDC_BANDWIDTH_EDIT              1024
#define IDC_IP_TYPE_EDIT                1025
#define IDC_USERNAME_EDIT               1026
#define IDC_AUTO_ANSWER_CHECK           1027
#define IDC_DTMF_AS_STRING_CHECK        1028
#define IDC_DISABLE_H242_CHECK          1029
#define IDC_DISABLE_FASTSTART           1030
#define IDC_RING_FILE_EDIT              1031
#define IDC_RING_FILE_BROWSE            1032
#define IDC_RING_FILE_PLAY              1033
#define IDC_CHECK_SEND_VIDEO            1037
#define IDC_CHECK_RECEIVE_VIDEO         1038
#define IDC_CHECK_LOCALVIDEO            1039
#define IDC_LVFLIP                      1040
#define IDC_LHFLIP                      1041
#define IDC_VIDEOBITMAP                 1041
#define IDC_RVFLIP                      1042
#define IDC_VIDEOBITMAP1                1042
#define IDC_RHFLIP                      1043
#define IDC_SLVIDEO                     1043
#define IDC_SRVIDEO                     1044
#define IDC_BHOMEPAGE                   1045
#define IDC_MICIND                      1046
#define IDC_VOLIND                      1047
#define IDC_SMYSTAT                     1049
#define IDC_INMSGCLR                    1050
#define IDC_OUTMSGCLR                   1051
#define IDC_ACTINDCLR                   1052
#define IDC_SLNDINDCLR                  1053
#define IDC_HIDEVIDEOCHK                1054
#define IDC_HIDESYSMSG                  1055
#define IDC_HIDESTAT                    1056
#define IDC_AUTOADDADDRESS              1057
#define IDC_SYSTRAYMIN                  1058
#define IDC_BCLEARDESTHIST              1059
#define IDC_BMIC                        1061
#define IDC_BSND                        1062
#define IDC_GKUSE                       1062
#define IDC_GKREG                       1063
#define IDC_GKREC                       1063
#define IDC_GKAUTODISCOVER              1064
#define IDC_GKAUTODISC                  1064
#define IDC_GKHOSTDISCOVER              1065
#define IDC_GKHOSTDISC                  1065
#define IDC_GKIDDISCOVER                1066
#define IDC_GKIDDISC                    1066
#define IDC_GKIDEDIT                    1067
#define IDC_GKID                        1067
#define IDC_GKHOSTEDIT                  1068
#define IDC_GKHOST                      1068
#define IDC_GKPASSEDIT                  1069
#define IDC_ALIASESLIST                 1070
#define IDC_ALSADDBUTTON                1071
#define IDC_ALSDELLBUTTON               1072
#define IDC_ALIASEDIT                   1073
#define IDC_VIDEOQTY                    1074
#define IDC_VIDEOMAXBPS                 1075
#define IDC_VIDEOINMAXBPS               1075
#define IDC_VIDEOFPS                    1076
#define IDC_VQTYSPIN                    1077
#define IDC_VBPSSPIN                    1078
#define IDC_DESK                        1078
#define IDC_VINBPSSPIN                  1078
#define IDC_VFPSSPIN                    1079
#define IDC_GKPASSSTATIC                1080
#define IDC_VIDEOMAXBPS2                1080
#define IDC_VIDEOOUTMAXBPS              1080
#define IDC_LANGCOMBO                   1081
#define IDC_VBPSSPIN2                   1081
#define IDC_VOUTBPSSPIN                 1081
#define IDC_CALLSTATIC                  1082
#define IDC_CONSTATIC                   1083
#define IDC_AUDIOSTATIC                 1084
#define IDC_MSGSTATIC                   1085
#define IDC_VIDEOSTATIC                 1086
#define IDC_OUTDEVSTATIC                1087
#define IDC_INDEVSTATIC                 1088
#define IDC_BUFFSTATIC                  1089
#define IDC_JITSTATIC                   1090
#define IDC_CODECSSTATIC                1091
#define IDC_USERSTATIC                  1092
#define IDC_AGCSTATIC                   1092
#define IDC_UNAMESTATIC                 1093
#define IDC_NETWORKSTATIC               1094
#define IDC_BANDSTATIC                  1095
#define IDC_KBSSTATIC                   1096
#define IDC_IPTSTATIC                   1097
#define IDC_RINGSTATIC                  1098
#define IDC_GKSTATIC                    1099
#define IDC_UALIASESSTATIC              1100
#define IDC_UALEASSTATIC                1101
#define IDC_LANGSTATIC                  1102
#define IDC_COLSTATIC                   1103
#define IDC_COLMSGSTATIC                1104
#define IDC_COLAUDIOSTATIC              1105
#define IDC_COLLSTATIC                  1106
#define IDC_COLRSTATIC                  1107
#define IDC_COLASTATIC                  1108
#define IDC_COLSSTATIC                  1109
#define IDC_VDEVSTATIC                  1110
#define IDC_VDEVCHSTATIC                1111
#define IDC_VIEWSTATIC                  1112
#define IDC_QTYSTATIC                   1113
#define IDC_BPSSTATIC                   1114
#define IDC_CSSTATIC                    1115
#define IDC_FPSSTATIC                   1116
#define IDC_EDIT1                       1117
#define IDC_RTPBEDIT                    1117
#define IDC_ABOOKSRCHEDIT               1117
#define IDC_BPSSTATIC2                  1117
#define IDC_EDIT2                       1118
#define IDC_RTPMEDIT                    1118
#define IDC_ABOOKADRNAMEEDIT            1118
#define IDC_CSSTATIC2                   1118
#define IDC_EDIT3                       1119
#define IDC_NATREDIT                    1119
#define IDC_ABOOKADRADREDIT             1119
#define IDC_EDIT4                       1120
#define IDC_LOCALIEDIT                  1120
#define IDC_ABOOKADRRINGEDIT            1120
#define IDC_RTPBSTATIC                  1121
#define IDC_RTPMSTATIC                  1122
#define IDC_NATRSTATIC                  1123
#define IDC_LOCISTATIC                  1124
#define IDC_ABOOKADRNAMESTATIC          1130
#define IDC_ABOOKADRNAMEEDITBUTTON      1131
#define IDC_ABOOKADRADRSTATIC           1132
#define IDC_ABOOKADRADDBUTTON           1134
#define IDC_ABOOKADRDELBUTTON           1135
#define IDC_ABOOKADRRINGSTATIC          1136
#define IDC_ABOOKOUTCLRBUTTON           1138
#define IDC_ABOOKINLIST                 1145
#define IDC_ABOOKADROUTBUTTON           1146
#define IDC_ABOOKMSDADDBUTTON           1147
#define IDC_ABOOKMSDCLRBUTTON           1148
#define IDC_ABOOKINADDBUTTON            1149
#define IDC_ABOOKINCLRBUTTON            1150
#define IDC_ABOOKADRLIST                1151
#define IDC_ABOOKMSDLIST                1153
#define IDC_ABOOKOUTLIST                1154
#define IDC_VIDEOSIZE                   1155
#define IDC_VIDEOINSIZE                 1155
#define IDC_VSIZE                       1156
#define IDC_SMARTCODEC                  1157
#define IDC_HIDEPNPCHECK                1158
#define IDC_VSIZE2                      1158
#define IDC_LOCFLIPCHECK                1159
#define IDC_VIDEOSIZE2                  1160
#define IDC_VIDEOOUTSIZE                1160
#define IDC_STATIC2                     1160
#define IDC_STRICT_SINGLE_LINE          1164
#define IDC_FULLSCRDEFLT                1165
#define IDC_AUTO_MUTE_CHECK             1166
#define ID_MSETTINGS                    32771
#define ID_MABOUT                       32772
#define ID_LOGMENU_COPY                 32774
#define ID_LOGMENU_CLEARLOG_OK          32776
#define ID_LOGMENU_SELECTALL            32777
#define ID_DESTMENU_COPY                32780
#define ID_DESTMENU_PASTE               32781
#define ID_DESTMENU_CLEARADDRESSES_ALL  32785
#define ID_MHELP                        32786
#define ID_QQQQQQQ                      32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1167
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
